config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events
  get :get_events, to: 'events#get_events'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  include StubhubApi

  has_many :prices, dependent: :destroy

  def metadata_hash
    JSON.parse(metadata)
  end

  # write a test for this
  # price from api
  def get_price
    get_lowest_price(event_id)
  end

  # test
  def get_most_recent_price
    self.prices.order("created_at desc").first
  end

  # test
  def new_price(price)
    return nil unless price

    current_price = self.get_most_recent_price
    if current_price&.current == price[:current_price]
      current_price.update(updated_at: Time.current)
    else
      self.prices << Price.create(current: price[:current_price], listing: price[:listing_price])
    end
  end

  def graph_prices
    @graph_prices = self.prices.order('created_at desc').flat_map do |p|
      [[p.created_at, p.current],
      [p.updated_at, p.current]]
    end.to_h

    return @graph_prices
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # write a test going to index and show page

  include Api::Stubhub

  before_action :set_event, only: []

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    unless event_id = params[:id]
      redirect_to root_path
    end

    unless @event = Event.find_by(event_id: event_id)
      event_metadata = get_event(event_id)["events"]&.first
      @event = Event.create(name: event_metadata["name"], event_id: event_id, metadata: event_metadata&.to_json)
    end

    price = @event.get_price
    @event.new_price(price)

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_events
    events = get_list_of_events(params[:event])
    render json: events
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_info_block.html.erb
<%= content_tag :div, class: "overflow" do %>
  
  <%= content_tag :div, class: "col-sm-4 nmnp" do %>
    <%= content_tag :div, class: "block-3 blue overflow-scroll" do %>
      <%= content_tag :div, class: "event-information" do %>
        <%= @event.metadata_hash.each do |key, value| %>
          <% if value.class == String %>
            <%= "#{key}: #{value}" %>
            <br/>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag :div, class: "col-sm-4 nmnp" do %> 
      <%= react_component("EventWatch") %>

  <% end %>

  <%= content_tag :div, class: "col-sm-4 nmnp" do %>
    <%= content_tag :div, class: "block-1 blue" do %>
      <%= content_tag :div, class: "event-current-price-title", align: "center" do %>
        Current Price
      <% end %>
      <%= content_tag :div, class: "event-current-price-amount", align: "center" do %>
        <%= "$#{@event.get_most_recent_price&.current.to_s}" %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag :div, class: "col-sm-4 nmnp" do %>
    <%= content_tag :div, class: "block-1-1 blue" do %>
      <%= content_tag :div, class: "event-current-price-title", align: "center" do %>
        Listing Price
      <% end %>
      <%= content_tag :div, class: "event-current-price-amount", align: "center" do %>
        <%= "$#{@event.get_most_recent_price&.listing.to_s}" %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag :div, class: "col-sm-8 nmnp" do %>
    <%= content_tag :div, class: "block-1-1 blue" do %>
      <%= line_chart @event.graph_prices, min: nil, max: nil, adapter: "google", 
        height: '100%', width: '100%',
        library: {
          title: "Prices Over Time",
          # titleTextStyle: { color: "white" },
          chartArea:{left:10,right:10,height:'80%',width:'80%'},
          pointSize: 0, 
          animation: { easing: 'easeOutQuad' }, 
          # backgroundColor: "rgb(35,162,255)", 
          # colors: ['#ffffff'],
          # vAxis: {textStyle: { color: "#ffffff" }},
          # hAxis: {textStyle: { color: "#ffffff" }},
        }
      %>
    <% end %>
  <% end %>

<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= react_component("EventSearch") %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%#= link_to 'Back', events_path %>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdn.rawgit.com/nnattawat/flip/master/dist/jquery.flip.min.js"></script>

<div>
  <%= content_tag :div, class: "col-lg-offset-2 col-lg-8 col-md-offset-1 col-md-10 no-pad" do %>
    <%= content_tag :div, class: "event-image-trim" do %>
      <%= image_tag @event.metadata_hash["imageUrl"], class: "event-image" %>
    <% end if false %>
    <%= content_tag :div do %>
      <%= content_tag :div, class: "event-title", align: 'center' do @event.name end %>
      <%= render 'event_info_block' %>
      <%#= line_chart @event.graph_prices, min: nil, max: nil, adapter: "google", 
          library: {pointSize: 0, animation: { easing: 'easeOutQuad' }} %>
    <% end %>
  <% end %>
</div>